name: webapp CI

on:
  pull_request_target:
    branches:  main 
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-client

    - name: Start PostgreSQL service
      run: |
        sudo systemctl start postgresql.service
        sudo systemctl enable postgresql.service
        sudo systemctl status postgresql.service

    - name: Wait for PostgreSQL to be ready
      run: until pg_isready -h localhost -p 5432;

    - name: Create PostgreSQL user and database
      run: |
        sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER CREATEDB PASSWORD '${{ secrets.DB_PASS }}';"
        sudo -u postgres createdb ${{ secrets.DB_NAME }}
    
    - uses: actions/checkout@v2

    - name: Setup NodeJS Environment
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 5432
      run: npm test